# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cantango-roles}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kristian Mandrup}]
  s.date = %q{2011-12-09}
  s.description = %q{Roles and Role groups for CanTango}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "lib/cantango/roles.rb",
    "lib/cantango/roles_ext.rb",
    "lib/cantango/roles_ext/ability.rb",
    "lib/cantango/roles_ext/ability/helper.rb",
    "lib/cantango/roles_ext/ability/helper/role.rb",
    "lib/cantango/roles_ext/ability/helper/role_group.rb",
    "lib/cantango/roles_ext/builder.rb",
    "lib/cantango/roles_ext/builder/permit.rb",
    "lib/cantango/roles_ext/builder/permit/role.rb",
    "lib/cantango/roles_ext/builder/permit/role_group.rb",
    "lib/cantango/roles_ext/configuration.rb",
    "lib/cantango/roles_ext/configuration/registry/role.rb",
    "lib/cantango/roles_ext/configuration/role_groups.rb",
    "lib/cantango/roles_ext/configuration/roles.rb",
    "lib/cantango/roles_ext/configuration/system.rb",
    "lib/cantango/roles_ext/engine.rb",
    "lib/cantango/roles_ext/engine/permits.rb",
    "lib/cantango/roles_ext/filter.rb",
    "lib/cantango/roles_ext/filter/role.rb",
    "lib/cantango/roles_ext/filter/role_group.rb",
    "lib/cantango/roles_ext/helpers.rb",
    "lib/cantango/roles_ext/helpers/role.rb",
    "lib/cantango/roles_ext/helpers/role_group.rb",
    "lib/cantango/roles_ext/permit.rb",
    "lib/cantango/roles_ext/permit/helper/role_matcher.rb",
    "lib/cantango/roles_ext/permit/role.rb",
    "lib/cantango/roles_ext/permit/role_group.rb",
    "lib/generators/cantango/base.rb",
    "lib/generators/cantango/basic.rb",
    "lib/generators/cantango/license_base.rb",
    "lib/generators/cantango/permit_generator.rb",
    "lib/generators/cantango/role_permit/role_permit_generator.rb",
    "lib/generators/cantango/role_permit/templates/account_permit.erb",
    "lib/generators/cantango/role_permit/templates/role_group_permit.erb",
    "lib/generators/cantango/role_permit/templates/role_permit.erb",
    "lib/generators/cantango/role_permits/role_permits_generator.rb",
    "spec/cantango/ability/helper/role_group_spec.rb",
    "spec/cantango/ability/helper/role_spec.rb",
    "spec/cantango/ability/helper/shared/role_ex.rb",
    "spec/cantango/ability/helper/shared/role_group_ex.rb",
    "spec/cantango/builder/role_group_spec.rb",
    "spec/cantango/builder/role_spec.rb",
    "spec/cantango/configuration/role_groups_spec.rb",
    "spec/cantango/configuration/role_registry_spec.rb",
    "spec/cantango/configuration/roles_spec.rb",
    "spec/cantango/configuration/shared/registry_ex.rb",
    "spec/cantango/configuration/shared/role_registry_ex.rb",
    "spec/cantango/configuration/shared/system_ex.rb",
    "spec/cantango/configuration/system_spec.rb",
    "spec/cantango/engine/permits_spec.rb",
    "spec/cantango/filter/role_group_spec.rb",
    "spec/cantango/filter/role_spec.rb",
    "spec/cantango/helpers/role_group_spec.rb",
    "spec/cantango/helpers/role_spec.rb",
    "spec/fixtures/models.rb",
    "spec/fixtures/models/admin.rb",
    "spec/fixtures/models/admin_account.rb",
    "spec/fixtures/models/items.rb",
    "spec/fixtures/models/permission.rb",
    "spec/fixtures/models/project.rb",
    "spec/fixtures/models/simple_roles.rb",
    "spec/fixtures/models/user.rb",
    "spec/fixtures/models/user_account.rb",
    "spec/helpers/current_user_accounts.rb",
    "spec/helpers/current_users.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/cantango-roles}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Roles extension for CanTango}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<sweetloader>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<cantango-config>, ["~> 0.1.9"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1"])
      s.add_dependency(%q<sugar-high>, [">= 0.6.1"])
      s.add_dependency(%q<sweetloader>, [">= 0.1.6"])
      s.add_dependency(%q<hashie>, [">= 1.2.0"])
      s.add_dependency(%q<cantango-config>, ["~> 0.1.9"])
      s.add_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1"])
    s.add_dependency(%q<sugar-high>, [">= 0.6.1"])
    s.add_dependency(%q<sweetloader>, [">= 0.1.6"])
    s.add_dependency(%q<hashie>, [">= 1.2.0"])
    s.add_dependency(%q<cantango-config>, ["~> 0.1.9"])
    s.add_dependency(%q<bundler>, [">= 1.1.rc"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

